### ISSUE TITLE
Java standalone example

### ISSUE THREAD

**Issue by alvarogarcia7** [france-connect/service-providers-examples#2]
Hello,

I've created a standalone java example in this repo: https://github.com/alvarogarcia7/franceconnect-openid-example

Could you please add it to the corresponding repo?

Thanks in advance,

**Comment by fpetitit** [comment]
Hi Alvaro,

do you prefer that we add this repo to the FranceConnect one, or just add a link into the README file : 
https://github.com/france-connect/service-providers-examples ?
